/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    HologramComponentInspector: typeof import('./../components/hologram/ComponentInspector.vue')['default']
    HologramComponentTree: typeof import('./../components/hologram/ComponentTree.vue')['default']
    HologramConnectionBadge: typeof import('./../components/hologram/ConnectionBadge.vue')['default']
    HologramDevtoolsLayout: typeof import('./../components/hologram/DevtoolsLayout.vue')['default']
    HologramInspectorSection: typeof import('./../components/hologram/InspectorSection.vue')['default']
    HologramLiveStateValue: typeof import('./../components/hologram/LiveStateValue.vue')['default']
    HologramPanelsComponentsPanel: typeof import('./../components/hologram/panels/ComponentsPanel.vue')['default']
    HologramPanelsOverviewPanel: typeof import('./../components/hologram/panels/OverviewPanel.vue')['default']
    HologramPanelsPagesPanel: typeof import('./../components/hologram/panels/PagesPanel.vue')['default']
    HologramPanelsResourcesPanel: typeof import('./../components/hologram/panels/ResourcesPanel.vue')['default']
    HologramPanelsTimelinePanel: typeof import('./../components/hologram/panels/TimelinePanel.vue')['default']
    HologramResourceInspector: typeof import('./../components/hologram/ResourceInspector.vue')['default']
    HologramStateValue: typeof import('./../components/hologram/StateValue.vue')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    TestComponent: typeof import('./../components/TestComponent.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
    UApp: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UInput: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UTooltip: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
